### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by Antoine4011** [naoty/Timepiece#36]
With the new Apple TV, the support for tvOS would be great. :)

**Comment by naoty** [comment]
Thank you! But, I'm have not enough time to

**Comment by naoty** [comment]
Thank you! But, I have not enough time to research tvOS and implement features for it. Welcome to your Pull request!

**Comment by nickygerritsen** [comment]
I will create a PR for this, but it will be based of Swift 2.0 of course.

Do you have any plans to soon merge this into master? As swift 2.0 is now released.

**Comment by naoty** [comment]
@nickygerritsen Sorry for the delay! I'll try merge `swift-2` branch into `master`. :bow:

**Comment by Jamonek** [comment]
👍🏽

**Comment by Jamonek** [comment]
Hi Greg,

You’ve been invited by Jamone to join the Dropbox Campus Cup! Campus Cup lets you team up with your classmates to earn up to 25 GB of free Dropbox space for two years!

To earn space, just invite friends and use Dropbox to share, collaborate, and get work done.

Join Campus Cup![2]

Note that you must be a student currently enrolled at a higher education institution in order to participate. Learn more about Campus Cup.[3]

Happy Dropboxing!


 
 Work together, win together. 

____________________________________________________
If you prefer not to receive invites from Dropbox, please go here[4].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/xSPaemVllDVEMCdfZ9pIRG/campuscup?text=1
[2]: https://www.dropbox.com/l/dDtDaudBZ2RlLbXacwiwuj/campuscup?text=1
[3]: https://www.dropbox.com/l/cBvR1xvn2Gx7rF2xsJkAhr/help/9131?text=1
[4]: https://www.dropbox.com/l/BoP854ExDUmT698TIWmE4z?text=1
