### ISSUE TITLE
Carthage: Problems during Build for iOS

### ISSUE THREAD

**Issue by innoreq** [naoty/Timepiece#50]
I'm using Carthage to get Timepiece included into my project. However, there is a problem during build:

```Swift

ld: warning: directory not found for option '-F/Users/gschneider/Development/ws.42/hfmain/Configuration/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Carthage/Build/iOS'
ld: building for iOS simulator, but linking against dylib built for OSX, file '/Users/gschneider/Development/ws.42/hfmain/Configuration/Carthage/Checkouts/Timepiece/Build/Products/Release/Timepiece.framework/Timepiece' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Any idea how to fix that? I just perform `carthage update` and proceeded according to the Carthage instructions.

**Comment by basememara** [comment]
I believe this is a Carthage thing. Depending on how you are adding your dependencies, Xcode will automatically add them to the "Framework Search Paths" under the "Build Settings" tab. You can remove these from the target because Xcode treats them as implicit dependencies due to them being in the same workspace if this is how you set it up. Select the target, locate the "Framework Search Paths" setting, highlight it, and remove the Timepiece path.

**Comment by naoty** [comment]
@innoreq Did you solve this issue? I'll close this issue, but if you are still in trouble, I'll reopen it.

**Comment by innoreq** [comment]
I’m using Timepiece via Cocoapods now, this is working fine now (after struggling with Cocoapods in general for some time…).

Thanks for your engagement!
