### ISSUE TITLE
can't change the begin time of day

### ISSUE THREAD

**Issue by 861645007** [naoty/Timepiece#51]
你好：我在尝试设置今天的开始时间（就是0点0分），但是获取的结果不正确。代码如下
![1ea4142f-6161-410b-bf68-9cdee780dcb4](https://cloud.githubusercontent.com/assets/7790051/12648660/febfb172-c615-11e5-9337-a43498530f04.png)
![bebb3a14-359b-4bee-89b5-8e0d6040117e](https://cloud.githubusercontent.com/assets/7790051/12648661/ff1e5876-c615-11e5-9bb5-22e9ac827fc0.png)

**Comment by 861645007** [comment]
我怀疑是不是时区的问题呢？但是我不知道怎么改，还请麻烦您看下。

**Comment by naoty** [comment]
I don't understand Chinese. Would you tell me your issue in English?

**Comment by 861645007** [comment]
Sorry: my English is not good.
 I am trying to set the start time of today (for example： 2016-01-29 00:00:00), but the result is not right. Code as follows:
![1ea4142f-6161-410b-bf68-9cdee780dcb4](https://cloud.githubusercontent.com/assets/7790051/12666694/2782c438-c67e-11e5-8192-275305e434d5.png)
![bebb3a14-359b-4bee-89b5-8e0d6040117e](https://cloud.githubusercontent.com/assets/7790051/12666695/27da47bc-c67e-11e5-90be-7b1727e48d54.png)

**Comment by 861645007** [comment]
I suspect that this problem is related to the time zone? But I do not know how to change, but also please trouble you.

**Comment by 861645007** [comment]
Hi,sir:
I'm so sorry to bother you, but I really don't know how to solve this problem. Please, help me.

**Comment by naoty** [comment]
There is something wrong... I'll try to investigate this problem! Thank you for reporting.

**Comment by 861645007** [comment]
Thank you for your efforts, look forward to your results, thank you

**Comment by naoty** [comment]
@861645007 Sorry for late reply! I found that the result of `print(date)` looks strange, but actually `todayEnd.hour` returns `0`. Screenshots are here.

![2016-02-13 20 55 34](https://cloud.githubusercontent.com/assets/413899/13027450/3d1cf4d6-d294-11e5-8dc6-ed204ddfca10.png)
![2016-02-13 20 55 41](https://cloud.githubusercontent.com/assets/413899/13027453/3fa66282-d294-11e5-8b52-ad6eeb55bfbb.png)

This problem is caused by the wrong implementation of `CustomStringConvertible` for extended `NSDate`. This protocol defines a customized text format returned by `print` and so on.

**Comment by naoty** [comment]
It seems that the override of `description`, which is defined at `CustomStringConvertible`, is not allowed. I don't know how to solve this problem...

**Comment by 861645007** [comment]
I think that the problem is UTC and GMT。we can get UTC of time from `NSDate()`, but current time which we print is GMT, It is a difference of 8 hours（when i use beijing time）

![aa2e84e1-6cae-42ae-93a1-f65490a52e21](https://cloud.githubusercontent.com/assets/7790051/13031738/92f2726e-d311-11e5-8c71-886955714f45.png)

**Comment by 861645007** [comment]
I don't know if my guess is right, please look at it.

**Comment by naoty** [comment]
Yes, your guess is right. The result of `print` ignores the timezone because the implementation of `CustomStringConvertible` for extended `NSDate` doesn't consider the timezone. If possible, I want to override `describe` property to consider the timezone. But, it seems that the override is not allowed...

**Comment by 861645007** [comment]
hi:
 I think you can use this method to change the time. Although this is not a good way, it can be a temporary solution to this problem. i hope you can find a better method.

`func tolocalTime() -> NSDate {
        let tz = NSTimeZone.localTimeZone()
        let seconds: NSInteger = tz.secondsFromGMTForDate(self)
        return NSDate(timeInterval: Double(seconds), sinceDate: self)
    }`

**Comment by 861645007** [comment]
```
func tolocalTime() -> NSDate {
        let tz = NSTimeZone.localTimeZone()
        let seconds: NSInteger = tz.secondsFromGMTForDate(self)
        return NSDate(timeInterval: Double(seconds), sinceDate: self)
    }
```

**Comment by naoty** [comment]
@861645007 If you want to change the timezone, you should use `-change(timeZone:)` at [here](https://github.com/naoty/Timepiece/blob/master/Sources/NSDate+Timepiece.swift#L141).

BTW, would you change the title of this issue in English?

**Comment by 861645007** [comment]
` -change(timeZone:)` this method can't play  a part in this problem

**Comment by naoty** [comment]
@861645007 Could you send a pull request includes tests regenerating your problem and codes solving them?
