### ISSUE TITLE
How to modify the time zone

### ISSUE THREAD

**Issue by shiqianren** [naoty/Timepiece#80]
How to modify the time zone，Get today's time is wrong（ NSDate.today()）

**Comment by naoty** [comment]
There is not such a feature. If the return value of `Date.today()` have wrong time zone, you should use a calendar different from `Calendar.current`, because Timepiece uses `Calendar.current`.

**Comment by shiqianren** [comment]
sorry  i can't understand  ( use a calendar different from Calendar.current instead of this library) ? ? ?

**Comment by naoty** [comment]
If you use a calendar different from `Calendar.current` such as `Calendar(identifier: .chinese)` or `Calendar(identifier: .buddhist)`, the return value of `Date.today()` may be wrong, because Timepiece always uses `Calendar.current` to calculate dates.

So, if you want to modify time zone, you should use another library.

**Comment by naoty** [comment]
@shiqianren I will close this issue. But, if your question is not solved yet, I will reopen this.
