### ISSUE TITLE
Change the default calendar

### ISSUE THREAD

**Issue by satoshi-takano** [naoty/Timepiece#92]
I want to change the default calendar. Because if someone uses Japanese calendar,  `Date().year`  returns the year in Japanese but I don't expect the behavior.

I suggest the changes below.
```swift
Date.defaultCalendar = .gregorian // Fix the default calendar to gregorian calendar.
Date().year // It'll always returns the year in gregorian calendar.
```

What do you think? If you agree to my suggestion, I'll make a pull request.

**Comment by naoty** [comment]
Thank you for suggestion! 😄 

I disagree with `Date.defaultCalendar`. It is confusing because `Date` object is a just value and independent of the calendar setting in iOS.

Instead, below method will fill your need.

```swift
Date().changed(on: .japanese)
```

Currently, `changed()` calculates date components with `Calendar.current`, and so `on calendar: Calendar` argument will be useful for you.

**Comment by satoshi-takano** [comment]
Thank you for quick response! 😀
I think your idea is good way to change the calendar. I'll try it.

**Comment by naoty** [comment]
Sorry for less description. This method is not implemented yet. So, if you want it, please send a pull request!

**Comment by satoshi-takano** [comment]
Thank you for description!
I decided to use `Calendar` directly to get year in Gregorian calendar.  Because I noticed that Timepiece’s conveniences is based on Extension and I can’t add calendar as a stored property(I don’t want use Associated Object).
